import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  ViewSuperior: {
    width: '100%',
    maxWidth: 360,
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  tituloTela: {
    fontSize: 28,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  subtituloTela: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 24,
  },
  segundaCamada: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 2,
  },
  TerceiraCamada: {
    width: '100%',
    gap: 14,
    marginBottom: 20,
  },
  campoContainer: {
    width: '100%',
    gap: 6,
  },
  labelInput: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
  },
  Input: {
    width: '100%',
    height: 46,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  InputFocado: {
    width: '100%',
    height: 46,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 8,
    paddingHorizontal: 12,
    borderWidth: 1.5,
    borderColor: '#1ABC9C',
  },
  textInput: {
    flex: 1,
    color: '#1F2937',
    fontSize: 14,
  },
  Botao: {
    width: '100%',
    height: 46,
    backgroundColor: '#1ABC9C',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
  },
  textoBotao: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  erroText: {
    color: '#EF4444',
    fontSize: 12,
    textAlign: 'left',
    marginTop: 2,
  },
  rodapeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    paddingBottom: 20,
  },
  textoRodape: {
    fontSize: 13,
    color: '#6B7280',
  },
  linkRodape: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1ABC9C',
  },
   input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F7FA',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#E1E8EF',
    paddingHorizontal: 15,
    height: 55,
    marginBottom: 15,
  },
  textInputInner: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
});
